version: '3.8'

services:
  backend:
    build:
      context: ../denis-play-backend
      dockerfile: Dockerfile
    image: play-backend:latest
    ports:
      - '5000:5000'
    networks:
      - appnet

  dvwa:
    image: vulnerables/web-dvwa
    depends_on:
      - db
    environment:
      MYSQL_PASS: dvwa
    ports:
      - '8081:80'
    networks:
      - appnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dvwa
      MYSQL_DATABASE: dvwa
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
