version: '3.8'

services:
  backend:
    build:
      context: ../denis-play-backend
      dockerfile: Dockerfile
    container_name: play-backend
    ports:
      - "5000:5000"
    depends_on:
      - dvwa
    networks:
      - appnet

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    environment:
      - MYSQL_PASS=dvwa
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    container_name: dvwa-db
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
