version: '3'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    environment:
      - MYSQL_PASS=dvwa
      - MYSQL_DATABASE=dvwa  # Definindo o banco de dados correto
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dvwa
      MYSQL_DATABASE: dvwa  # Certifique-se de que o banco seja 'dvwa'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
