name: Cypress Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'cypress/**'
      - 'Dockerfile'
      - '.github/workflows/run-cypress.yml'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Dar permissão para Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Rodar testes Cypress
        run: npm run cypress:run

      - name: Criar diretório de relatórios (caso não exista)
        run: mkdir -p cypress/reports/html/

      - name: Salvar resultados
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports/html/
